// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4wtOb9vqi_Y-Z8M7p4MKPyzPC6d9F1Q',
    appId: '1:508258349755:web:d9edc88d3b022aeac2ef9e',
    messagingSenderId: '508258349755',
    projectId: 'airguardai',
    authDomain: 'airguardai.firebaseapp.com',
    storageBucket: 'airguardai.firebasestorage.app',
    measurementId: 'G-Y5SLT9B2M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08gnAdT5PrfkczO63mC0X0Rpj2cjrcf0',
    appId: '1:508258349755:android:37d48211b044b26fc2ef9e',
    messagingSenderId: '508258349755',
    projectId: 'airguardai',
    storageBucket: 'airguardai.firebasestorage.app',
  );
}
